### ISSUE TITLE
1.3 branch implicitly converting Integer to Quantity for Divide operation

### ISSUE THREAD

**Issue by c-schuler** [cqframework/clinical_quality_language#336] opened 2018-06-04 23:32 UTC
The following expression:
`define Divide10: 1 / 0`

Produces the following ELM:
```
<def name="Divide10" context="Population" accessLevel="Public">
	<expression xsi:type="Divide">
		<operand xsi:type="ToQuantity">
			<operand valueType="t:Integer" value="1" xsi:type="Literal"/>
                </operand>
		<operand xsi:type="ToQuantity">
			<operand valueType="t:Integer" value="0" xsi:type="Literal"/>
                </operand>
	</expression>
</def>

```

According to the [spec](http://cql.hl7.org/2018May/09-b-cqlreference.html#divide), Integer types should be implicitly converted to Decimal types for the Divide operation.

**Comment by brynrhodes** [comment] 2018-06-06 15:47
I am not able to reproduce this with the regression tests in the translator, or with the given expression. I get the expected result of a Divide with conversion of the operands to Decimal. Do you get this result in isolation or is it part of a larger context?

**Comment by brynrhodes** [comment] 2018-09-25 00:19
Closing as not reproducible. Please feel free to reopen if you can provide more details.

**Closed by brynrhodes** 2018-09-25 00:19 UTC
