### ISSUE TITLE
CQL-to-ELM Translator unresponsive

### ISSUE THREAD

**Issue by ChristopherTJaramillo** [cqframework/clinical_quality_language#510] opened 2020-04-15 00:35 UTC
With certain large libraries, the translator becomes unresponsive.

**Comment by brynrhodes** [comment] 2020-04-15 01:44
Thank you for the report, I have reproduced this problem and am working on a root cause now.

**Comment by brynrhodes** [comment] 2020-06-11 00:14
After investigation, this is related to a known issue with the version of Antlr. See issue #343 for a description of the issue.

**Comment by brynrhodes** [comment] 2020-06-21 17:55
Closing as a duplicate of #343

**Closed by brynrhodes** 2020-06-21 17:55 UTC
Labels: bug
