### ISSUE TITLE
Warning Messages coming out in the ELM Files

### ISSUE THREAD

**Issue by jackcmeyer** [cqframework/clinical_quality_language#130] opened 2017-06-20 18:00 UTC
Hi @brynrhodes,

When working with CQL 1.2, we have noticed that warning messages are appearing in the ELM output. Is there a way to turn off the warning messages from appearing in the output?

For reference, the following CQL and ELM is what we are working with. 

```
library TESTCODE version '0.0.003'

using QDM version '5.0.2'

codesystem "LOINC:2.46": 'urn:oid:2.16.840.1.113883.6.1' version 'urn:hl7:version:2.46'

codesystem "SNOMEDCT:2016-03": 'urn:oid:2.16.840.1.113883.6.96' version 'urn:hl7:version:2016-03'

valueset "ONC Administrative Sex": 'urn:oid:2.16.840.1.113762.1.4.1'

valueset "Jack": 'urn:oid:1.1.1.1'

valueset "Race": 'urn:oid:2.16.840.1.114222.4.11.836'

valueset "Ethnicity": 'urn:oid:2.16.840.1.114222.4.11.837'

valueset "Payer": 'urn:oid:2.16.840.1.114222.4.11.3591'

parameter "Measurement Period" Interval<DateTime>

context Patient

define "SDE Ethnicity": ["Patient Characteristic Ethnicity": "Ethnicity"]

define "SDE Payer": ["Patient Characteristic Payer": "Payer"]

define "SDE Race": ["Patient Characteristic Race": "Race"]

define "SDE Sex": ["Patient Characteristic Sex": "ONC Administrative Sex"]
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<library xmlns="urn:hl7-org:elm:r1" xmlns:t="urn:hl7-org:elm-types:r1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:fhir="http://hl7.org/fhir" xmlns:a="urn:hl7-org:cql-annotations:r1">
   <annotation startLine="23" startChar="25" endLine="23" endChar="73" message="Retrieve has a terminology target but does not specify a code path and the type of the retrieve does not have a primary code path defined." errorType="semantic" errorSeverity="warning" xsi:type="a:CqlToElmError"/>
   <annotation startLine="23" startChar="25" endLine="23" endChar="73" message="Could not resolve membership operator for terminology target of the retrieve." errorType="semantic" errorSeverity="warning" xsi:type="a:CqlToElmError"/>
   <annotation startLine="25" startChar="21" endLine="25" endChar="61" message="Retrieve has a terminology target but does not specify a code path and the type of the retrieve does not have a primary code path defined." errorType="semantic" errorSeverity="warning" xsi:type="a:CqlToElmError"/>
   <annotation startLine="25" startChar="21" endLine="25" endChar="61" message="Could not resolve membership operator for terminology target of the retrieve." errorType="semantic" errorSeverity="warning" xsi:type="a:CqlToElmError"/>
   <annotation startLine="27" startChar="20" endLine="27" endChar="58" message="Retrieve has a terminology target but does not specify a code path and the type of the retrieve does not have a primary code path defined." errorType="semantic" errorSeverity="warning" xsi:type="a:CqlToElmError"/>
   <annotation startLine="27" startChar="20" endLine="27" endChar="58" message="Could not resolve membership operator for terminology target of the retrieve." errorType="semantic" errorSeverity="warning" xsi:type="a:CqlToElmError"/>
   <annotation startLine="29" startChar="19" endLine="29" endChar="74" message="Retrieve has a terminology target but does not specify a code path and the type of the retrieve does not have a primary code path defined." errorType="semantic" errorSeverity="warning" xsi:type="a:CqlToElmError"/>
   <annotation startLine="29" startChar="19" endLine="29" endChar="74" message="Could not resolve membership operator for terminology target of the retrieve." errorType="semantic" errorSeverity="warning" xsi:type="a:CqlToElmError"/>
   <identifier id="TESTCODE" version="0.0.003"/>
   <schemaIdentifier id="urn:hl7-org:elm" version="r1"/>
   <usings>
      <def localIdentifier="System" uri="urn:hl7-org:elm-types:r1"/>
      <def localId="1" locator="3:1-3:25" localIdentifier="QDM" uri="urn:healthit-gov:qdm:v5_0_1_draft" version="5.0.2"/>
   </usings>
   <parameters>
      <def localId="11" locator="19:1-19:49" name="Measurement Period" accessLevel="Public">
         <parameterTypeSpecifier localId="10" locator="19:32-19:49" xsi:type="IntervalTypeSpecifier">
            <pointType localId="9" locator="19:41-19:48" name="t:DateTime" xsi:type="NamedTypeSpecifier"/>
         </parameterTypeSpecifier>
      </def>
   </parameters>
   <codeSystems>
      <def localId="2" locator="5:1-5:87" name="LOINC:2.46" id="urn:oid:2.16.840.1.113883.6.1" version="urn:hl7:version:2.46" accessLevel="Public"/>
      <def localId="3" locator="7:1-7:97" name="SNOMEDCT:2016-03" id="urn:oid:2.16.840.1.113883.6.96" version="urn:hl7:version:2016-03" accessLevel="Public"/>
   </codeSystems>
   <valueSets>
      <def localId="4" locator="9:1-9:68" name="ONC Administrative Sex" id="urn:oid:2.16.840.1.113762.1.4.1" accessLevel="Public"/>
      <def localId="5" locator="11:1-11:34" name="Jack" id="urn:oid:1.1.1.1" accessLevel="Public"/>
      <def localId="6" locator="13:1-13:53" name="Race" id="urn:oid:2.16.840.1.114222.4.11.836" accessLevel="Public"/>
      <def localId="7" locator="15:1-15:58" name="Ethnicity" id="urn:oid:2.16.840.1.114222.4.11.837" accessLevel="Public"/>
      <def localId="8" locator="17:1-17:55" name="Payer" id="urn:oid:2.16.840.1.114222.4.11.3591" accessLevel="Public"/>
   </valueSets>
   <statements>
      <def locator="21:1-21:15" name="Patient" context="Patient">
         <expression xsi:type="SingletonFrom">
            <operand locator="21:1-21:15" xmlns:ns0="urn:healthit-gov:qdm:v5_0_1_draft" dataType="ns0:Patient" templateId="Patient" xsi:type="Retrieve"/>
         </expression>
      </def>
      <def localId="13" locator="23:1-23:73" name="SDE Ethnicity" context="Patient" accessLevel="Public">
         <annotation xsi:type="a:Annotation">
            <a:s r="13">
               <a:s>define &quot;SDE Ethnicity&quot;: </a:s>
               <a:s r="12">
                  <a:s>[&quot;Patient Characteristic Ethnicity&quot;: </a:s>
                  <a:s>
                     <a:s>&quot;Ethnicity&quot;</a:s>
                  </a:s>
                  <a:s>]</a:s>
               </a:s>
            </a:s>
         </annotation>
         <expression localId="12" locator="23:25-23:73" xmlns:ns1="urn:healthit-gov:qdm:v5_0_1_draft" dataType="ns1:PatientCharacteristicEthnicity" xsi:type="Retrieve">
            <codes name="Ethnicity" xsi:type="ValueSetRef"/>
         </expression>
      </def>
      <def localId="15" locator="25:1-25:61" name="SDE Payer" context="Patient" accessLevel="Public">
         <annotation xsi:type="a:Annotation">
            <a:s r="15">
               <a:s>define &quot;SDE Payer&quot;: </a:s>
               <a:s r="14">
                  <a:s>[&quot;Patient Characteristic Payer&quot;: </a:s>
                  <a:s>
                     <a:s>&quot;Payer&quot;</a:s>
                  </a:s>
                  <a:s>]</a:s>
               </a:s>
            </a:s>
         </annotation>
         <expression localId="14" locator="25:21-25:61" xmlns:ns2="urn:healthit-gov:qdm:v5_0_1_draft" dataType="ns2:PatientCharacteristicPayer" xsi:type="Retrieve">
            <codes name="Payer" xsi:type="ValueSetRef"/>
         </expression>
      </def>
      <def localId="17" locator="27:1-27:58" name="SDE Race" context="Patient" accessLevel="Public">
         <annotation xsi:type="a:Annotation">
            <a:s r="17">
               <a:s>define &quot;SDE Race&quot;: </a:s>
               <a:s r="16">
                  <a:s>[&quot;Patient Characteristic Race&quot;: </a:s>
                  <a:s>
                     <a:s>&quot;Race&quot;</a:s>
                  </a:s>
                  <a:s>]</a:s>
               </a:s>
            </a:s>
         </annotation>
         <expression localId="16" locator="27:20-27:58" xmlns:ns3="urn:healthit-gov:qdm:v5_0_1_draft" dataType="ns3:PatientCharacteristicRace" xsi:type="Retrieve">
            <codes name="Race" xsi:type="ValueSetRef"/>
         </expression>
      </def>
      <def localId="19" locator="29:1-29:74" name="SDE Sex" context="Patient" accessLevel="Public">
         <annotation xsi:type="a:Annotation">
            <a:s r="19">
               <a:s>define &quot;SDE Sex&quot;: </a:s>
               <a:s r="18">
                  <a:s>[&quot;Patient Characteristic Sex&quot;: </a:s>
                  <a:s>
                     <a:s>&quot;ONC Administrative Sex&quot;</a:s>
                  </a:s>
                  <a:s>]</a:s>
               </a:s>
            </a:s>
         </annotation>
         <expression localId="18" locator="29:19-29:74" xmlns:ns4="urn:healthit-gov:qdm:v5_0_1_draft" dataType="ns4:PatientCharacteristicSex" xsi:type="Retrieve">
            <codes name="ONC Administrative Sex" xsi:type="ValueSetRef"/>
         </expression>
      </def>
   </statements>
</library>
```

**Comment by brynrhodes** [comment] 2017-06-21 03:44
The warnings are caused by the QDM model info not declaring primaryCodePath for several of the data types. I corrected that in the QDM model info.

**Comment by cmoesel** [comment] 2017-06-21 15:27
Merged with #132

**Closed by cmoesel** 2017-06-21 15:27 UTC

**Comment by jackcmeyer** [comment] 2017-06-21 15:38
Is there any functionality to turn off warning messages from appearing in the ELM? Or is happening by design? It appears that toggling the annotation flag on/off does not have any impact on the warning messages.

**Comment by brynrhodes** [comment] 2017-06-22 06:11
There is currently not any functionality to disable warnings. Is this something that would be useful? The implementation was done so that the method for retrieving messages from the translator still returns only errors. Messages and Warnings musts be accessed either explicitly, or through the new Exceptions method (which returns messages, warnings, and errors). Of course, this doesn't apply to the ELM, all messages, warnings, and errors will be included in the resulting ELM.

If this is a desired feature, can you please submit an issue for the request?
