### ISSUE TITLE
DotNet : Some of cqlbaseVisitor and cqlparser class functions not there to override - throws error

### ISSUE THREAD

**Issue by sumitpkedia** [cqframework/clinical_quality_language#347] opened 2018-08-17 17:49 UTC
Hi, 

I could run dot net project in in VS 2013 version.
Also having nugets for ANTLR4 and IDE, VS SDK install.

I could build the project in VS 2013 but some of the functions from CQLBase class and cqlparser class doesnt seems to be available which is getting overridden in dot net project.

For ex: - LogicContext  is not present in cqlparser.
public override Element VisitLogic(cqlParser.LogicContext context) {}
And
ValuesetContext is not present in CqlVisitor with VisitValueset function
public override string VisitValueset(cqlParser.ValuesetContext context) 

Would really appreciate for help.

Thanks
Sumeet

**Comment by brynrhodes** [comment] 2018-08-29 01:14
I think this is a duplicate of #344, is that correct @sumitpkedia ?

**Closed** 2018-09-12 02:52 UTC
