### ISSUE TITLE
CQL to ELM conversion error

### ISSUE THREAD

**Issue by shardulbanker** [cqframework/clinical_quality_language#499] opened 2020-04-08 08:30 UTC
Hi,
I have configured project and performed all required steps before CQL to ELM conversion. Now I am using given CQL example file: ChlamydiaScreening_CQM.cql for ELM conversion but it is throwing below error.

Please let me know how to resolve this error and proceed further.

_D:\git_workspace\cql\Src\java\cql-to-elm\build\install\cql-to-elm\bin>cql-to-elm --input D:\git_workspace\cql\Examples\ChlamydiaScreening_CQM.cql
================================================================================
TRANSLATE D:\git_workspace\cql\Examples\ChlamydiaScreening_CQM.cql
Translation failed due to errors:
Warning:[37:14, 37:50] Could not resolve code path item.code for the type of the retrieve QUICK.DiagnosticOrder.
Warning:[37:14, 37:50] Could not resolve membership operator for terminology target of the retrieve.
Warning:[38:14, 38:44] Could not resolve code path item.code for the type of the retrieve QUICK.DiagnosticOrder.
Warning:[38:14, 38:44] Could not resolve membership operator for terminology target of the retrieve.
Warning:[39:14, 39:62] Could not resolve code path item.code for the type of the retrieve QUICK.DiagnosticOrder.
Warning:[39:14, 39:62] Could not resolve membership operator for terminology target of the retrieve.
Warning:[40:14, 40:81] Could not resolve code path item.code for the type of the retrieve QUICK.DiagnosticOrder.
Warning:[40:14, 40:81] Could not resolve membership operator for terminology target of the retrieve.
Error:[51:1, 51:18] Could not resolve context name Population in model QUICK._

Thanks and regards,
Shardul

**Comment by brynrhodes** [comment] 2020-04-08 14:36
Thank you for the report, it looks the issue is that since the example doesn't use a versioned reference to QUICK, when the new translator was released, it bumped the latest version of QUICK to 4.0.0. If you set the version of QUICK for that example to "1.6" that should address the issue. We will add this to the backlog to fix the examples based on the new version of QUICK.

**Comment by nehaghub** [comment] 2022-07-28 17:36
Hi,

I have configured project and performed all required steps before CQL to ELM conversion. 
When i am executing below command
C:\Documents\HDE\clinical_quality_language-master\clinical_quality_language-master\Src\java> ./cql-to-elm/build/install/cql-to-elm/bin/cql-to-elm --format=JSON --input ../../../../cql-execution-master/examples/node/age.cql --output ../../../../cql-execution-master/customCQL
I am getting this error

Error: Main method not found in class org.cqframework.cql.cql2elm.CqlTranslator, please define the main method 
as:
   public static void main(String[] args)
or a JavaFX application class must extend javafx.application.Application

Please let me know how to resolve this error .

Thank you.

**Comment by dqtran91** [comment] 2023-12-05 21:28
for the error: `Error:[51:1, 51:18] Could not resolve context name Population in model QUICK.` when running the example

I found commenting out the line, `context Population` works in `clinical_quality_language/Examples/ChlamydiaScreening_CQM.cql`

**Comment by JPercival** [comment] 2024-01-20 02:54
Closing as duplicate of #462

**Closed by JPercival** 2024-01-20 02:54 UTC
Labels: bug, help wanted, known issue
