### ISSUE TITLE
QDM 5.4 Model Info - frequency choiceType

### ISSUE THREAD

**Issue by p9g** [cqframework/clinical_quality_language#340] opened 2018-06-22 01:15 UTC
The frequency QDM attribute is defined as a System.code in the QDM 5.4 modelinfo [1].
Consider defining frequency as a choiceType to include code, quantity, decimal, and integer.

[1] https://github.com/cqframework/clinical_quality_language/blob/v13/Src/java/qdm/src/main/resources/gov/healthit/qdm/qdm-modelinfo-5.4.xml#L71

**Comment by brynrhodes** [comment] 2018-06-22 04:23
This is a great suggestion, we definitely have needed this, but I wonder if we should only support Quantity and Code? Because how would we be able to interpret an Integer or Decimal frequency?

**Comment by FEisenberg** [comment] 2018-06-22 13:42
Bryn, this comment came from a discussion in the QDM User Group.  The question was about whether QDM needed a frequency range attribute to accommodate as needed (PRN) dosing for calculations.  I explained the reason for code was to accommodate the various entries which might be text strings (e.g., every 4-6 hours, q4-6h, 4 to 6 times a day).  The expectation is that the local site would map their content to the codes.  I specifically asked for feedback about how entries exist today (i.e., based on a drop-down set of options, free text entries, etc.).  One response in the QDM Jira ticket (https://oncprojectracking.healthit.gov/support/projects/QDM/issues/QDM-205?filter=allopenissues) --- Obviously, any medication administered within the facility can be calculated after the fact, but discharge medications are more problematic to quantify frequency. Within MEDITECH, the frequency field points to a direction dictionary, which is populated by the individual hospital and can consist of values like "Q1-2HPRN" / "EVERY 1-2 HOURS AS NEEDED".  If frequency is needed for a medication without actual administration records, we would have to record it through the use of queries, which can be inconsistent.)  I don't understand how quantity works for frequency unless it means "quantity per day" - "supply" is supposed to provide quantity and frequency indicate the instruction for taking the medication (i.e., every 1-2 hours, etc).  I think we need to clearly define what we are requesting and what it should look like.  QDM was designed to identify frequency to determine #doses per day / supply (#doses) to calculate days supply.  If that is not the correct path for determining days supplied and it is defined separately then we may have an errata issue with QDM.

**Comment by brynrhodes** [comment] 2018-09-14 17:06
The related [QDM Issue](https://oncprojectracking.healthit.gov/support/browse/QDM-205) has been resolved, closing this issue as resolved by the updates to QDM 5.4.

**Closed by brynrhodes** 2018-09-14 17:06 UTC
Labels: enhancement
