### ISSUE TITLE
CQL-to-ELM Translator 1.4.6 - Internal Translator Error

### ISSUE THREAD

**Issue by JSRankins** [cqframework/clinical_quality_language#450] opened 2019-08-28 20:18 UTC
When provided the attached libraries, the CQL-to-ELM Translator results in, among other errors, an internal translator error that has no locator:

Error:[n/a] Internal translator error.

This makes it difficult for a tool using the Translator to provide users feedback on where the applicable error occurs. 

Is this an error in the translator, or was it intended by design?

Note: We had to attach the files as .txt files, since github does not support the attachment of .cql files.

[NCQA_Common-5.0.000.txt](https://github.com/cqframework/clinical_quality_language/files/3552721/NCQA_Common-5.0.000.txt)
[DMS_HEDIS_2020-3.0.002.txt](https://github.com/cqframework/clinical_quality_language/files/3552722/DMS_HEDIS_2020-3.0.002.txt)

**Comment by brynrhodes** [comment] 2019-09-03 23:35
Thank you for the reproduction, I was able to easily reproduce the problem.

The root cause is that the library being included is declared to use QDM version 5.4, but the main library is declared to use QDM version 5.5. When the included library is translated, it errors (correctly) when trying to load QDM 5.4 because 5.5 is already in use. However, because the error is encountered while loading the data model, the Patient context creation logic doesn't complete, leaving a partially constructed Patient expression. This partial Patient context results in an internal NullPointerException when the Patient context is referenced later in the included library. An internal error like that would normally be tagged with the location in the source code causing the error, but because the Patient expression isn't complete, the translator doesn't have a link to the parse tree to obtain that information.

I have a fix ready to apply, and will discuss with the impacted teams the best approach to getting the fix applied to the repository.

**Comment by brynrhodes** [comment] 2020-01-24 18:27
Addressed in 1.3.19-SNAPSHOT and 1.4.8-SNAPSHOT

**Closed by brynrhodes** 2020-01-24 18:27 UTC
Labels: bug
