### ISSUE TITLE
CQL formatter appending error String in code.

### ISSUE THREAD

**Issue by chinbaj** [cqframework/clinical_quality_language#220] opened 2017-08-24 16:57 UTC
When creating a parameter with syntax error, the CQL parser is appending error String inside the CQL code.

ex:
`parameter "test param" Interval<DateTime`

returns

```
parameter "test param" [java.lang.Exception: [1:40]: missing '>' at '<EOF>']

 Interval<DateTime.
```

**Comment by c-schuler** [comment] 2017-08-24 17:23
Hmm. I am unable to reproduce this. When I run `parameter "test param" Interval<DateTime`, I am getting the following back:
```
[java.lang.Exception: [1:40]: missing '>' at '<EOF>']

parameter "test param" Interval<DateTime
```
Which is the expected behavior. Are you using the most recent version of the formatter?

**Comment by JSRankins** [comment] 2017-08-24 17:27
@c-schuler, @brynrhodes  and @chinbaj, I believe the concern is getting the java error message back, which would then have to be caught and disposed of in an authoring tool before the original CQL that was passed through can be resurfaced to the user. Is there a reason the method is concatenating the error message with the original CQL expression?

**Comment by c-schuler** [comment] 2017-08-24 17:38
@JSRankins: I currently have a listener that detects syntax errors in the CQL and simply returns the error messages along with the original input. The reasoning is because "correctly" formatting syntax errors is hard =). I am open to suggestions on improving that.

**Comment by chinbaj** [comment] 2017-08-24 17:42
Agree with Stan.
@c-schuler , Are you testing against just the one expression or a complete CQL library.
I believe when you try to send in a single expression, the "[java.lang.Exception: ..." is appended at the top.
When you send in the entire CQL library, it gets inserted with the expression.

Either ways, since it comes back as a part of the library, the authoring tool UI shows it back on screen and causes further errors/confusion.

**Comment by c-schuler** [comment] 2017-08-24 17:51
Still unable to reproduce.
Tested:
```
library test version '0.0.000'
using QDM
valueset "Female Administrative Sex": '2.16.840.1.113883.3.560.100.2'
valueset "TestValueset": '1.1.111'
parameter "test param" Interval<DateTime
context Patient
define "TestDefinition":
	["Encounter, Performed": "TestValueset "]
```
Returned:
```
[java.lang.Exception: [10:0]: missing '>' at 'context']
library test version '0.0.000'
using QDM
valueset "Female Administrative Sex": '2.16.840.1.113883.3.560.100.2'
valueset "TestValueset": '1.1.111'
parameter "test param" Interval<DateTime
context Patient
define "TestDefinition":
	["Encounter, Performed": "TestValueset "]
```
Perhaps you can provide the library so I can test that?

How would you prefer the formatter to handle syntax errors?

**Comment by chinbaj** [comment] 2017-08-24 18:19
> The reasoning is because "correctly" formatting syntax errors is hard

Couldn't agree more. :-)

I checked further and the error insertion within the logic seems to be a side effect of the authoring tool code. So that's my bad.

But the larger point is that a library author is sending in a CQL library String and then getting back some additional Java exception messages as a part of the library.

> How would you prefer the formatter to handle syntax errors?

Is it possible to have a flag that we can set on the formatter?
Based on the this flag being set/not-set, formatter can prepend/not-prepend syntax errors to the output.

**Comment by c-schuler** [comment] 2017-08-24 18:24
> Is it possible to have a flag that we can set on the formatter?

Yeah, I can do that. The output in that case (when syntax errors are encountered) would be the original input without formatting. 

@brynrhodes: thoughts?

**Comment by chinbaj** [comment] 2017-08-24 22:06
@jackcmeyer : thoughts

**Comment by jackcmeyer** [comment] 2017-08-25 14:45
@chinbaj this sounds good to me

**Comment by brynrhodes** [comment] 2017-08-25 15:52
Yes, I like that solution, but I would want to verify that whether or not the error messages are included in the output, the errors are still available to the caller as structured exceptions, right?

**Comment by chinbaj** [comment] 2017-08-25 16:18
>  I would want to verify that whether or not the error messages are included in the output, the errors are still available to the caller as structured exceptions, right?

It would be nice If it could be done.

**Comment by c-schuler** [comment] 2017-08-25 16:52
Thanks for everyone's input. After discussion with Bryn, we believe the best solution is to return a structure like so:
Result(Errors[], input/output)

When there are errors in the CQL a list of errors will be returned with the original input. When no errors are encountered an empty error list will be returned with the formatted output.

If there aren't any objections, I will move forward with this implementation.

**Comment by chinbaj** [comment] 2017-08-25 17:03
Seems fine with me. Thanks a lot for making this change,

**Comment by brynrhodes** [comment] 2017-08-28 14:48
Addressed in v.1.2.13-SNAPSHOT

**Closed by brynrhodes** 2017-08-28 14:48 UTC
Labels: enhancement
