### ISSUE TITLE
Issue with ELM annotations during comparison operators to literals

### ISSUE THREAD

**Issue by mgramigna** [cqframework/clinical_quality_language#1131] opened 2023-02-22 16:15 UTC
Identified during an investigation for https://github.com/projecttacoma/fqm-execution/issues/202

I wanted to clarify/potentially report an issue on the expected structure of ELM annotations for certain CQL expressions. fqm-execution relies on these annotations in order to assemble measure logic highlighting HTML shown in the linked issue.

Consider the following simplified case from the issue:

``` cql
/* snipped library def and other expression referenced */

define "Example":
  "Expression That Returns Number" >= 66
```

Generates the following ELM with annotation:

``` json
{
  "localId": "8",
  "name": "Example",
  "context": "Patient",
  "accessLevel": "Public",
  "annotation": [
    {
      "type": "Annotation",
      "s": {
        "r": "8",
        "s": [
          {
            "value": ["", "define ", "\"Example\"", ":\n  "]
          },
          {
            "r": "7",
            "s": [
              {
                "r": "5",
                "s": [
                  {
                    "value": ["\"Expression That Returns Number\""]
                  }
                ]
              },
              {
                "r": "6",
                "value": [" ", ">=", " ", "66"]
              }
            ]
          }
        ]
      }
    }
  ],
  "expression": {
    "localId": "7",
    "type": "GreaterOrEqual",
    "operand": [
      {
        "localId": "5",
        "name": "Expression That Returns Number",
        "type": "ExpressionRef"
      },
      {
        "localId": "6",
        "valueType": "{urn:hl7-org:elm-types:r1}Integer",
        "value": "66",
        "type": "Literal"
      }
    ]
  }
}
```

Of note is that the `>=` string gets roped into the annotation for the literal `66`, corresponding to localId `"6"` in the ELM. Gut feeling causes me to think that the `>=` annotation be on its own in the annotation not tied to the literal expression. A slight modification of the CQL produces the desired annotation:

``` cql
/* snipped library def and other expressions referenced */

define "Example":
  "Expression That Returns Number" >= "Other Expression That Returns Number"
```

Generates the following very similar ELM, but with the desired annotation:

``` json
{
  "localId": "10",
  "name": "Example",
  "context": "Patient",
  "accessLevel": "Public",
  "annotation": [
    {
      "type": "Annotation",
      "s": {
        "r": "10",
        "s": [
          {
            "value": ["", "define ", "\"Example\"", ":\n  "]
          },
          {
            "r": "9",
            "s": [
              {
                "r": "5",
                "s": [
                  {
                    "value": ["\"Expression That Returns Number\""]
                  }
                ]
              },
              {
                "value": [" ", ">=", " "]
              },
              {
                "r": "8",
                "s": [
                  {
                    "value": ["\"Other Expression That Returns Number\""]
                  }
                ]
              }
            ]
          }
        ]
      }
    }
  ],
  "expression": {
    "localId": "9",
    "type": "GreaterOrEqual",
    "operand": [
      {
        "localId": "5",
        "name": "Expression That Returns Number",
        "type": "ExpressionRef"
      },
      {
        "localId": "8",
        "name": "Other Expression That Returns Number",
        "type": "ExpressionRef"
      }
    ]
  }
}
```

Here, the `>=` string is on its own in the annotation, and is not tied to the localId `"8"` ExpressionRef. The unexpected behavior only seems to happen when the LHS or RHS of a comparison expression is a literal, not an ExpressionRef or other more complex ELM expression.

**Main Question:** Is it an issue or is it expected behavior that the annotation for a comparison operator is not separated out from a literal when comparison is done to that literal?

If it is expected that the `>=` is tied to the literal, perhaps the `"r"` value should actually correspond to the "localId" of the `GreaterOrEqual` expression, not the `Literal`?

**Comment by JPercival** [comment] 2023-11-23 17:37
Duplicate of #1279

**Closed** 2024-01-05 22:16 UTC
Labels: bug
